on:
  push:
  workflow_dispatch:

env:
  awsregion: us-west-2
  awsaccountid: 987868780346
  ecr-reponame: todolist
  ecs-cluster-name: todolist

jobs:
  fargate:
    runs-on: ubuntu-latest
    steps:
    - name: Set Amazon ECR Registry DNS Name
      shell: pwsh
      run: |
        'ecr-registry=${{ env.awsaccountid }}.dkr.ecr.${{ env.awsregion }}.amazonaws.com' >> $env:GITHUB_ENV
    - name: Set Amazon ECR Repository
      shell: pwsh
      run: |
        'ecr-repository=${{ env.ecr-registry }}/${{ env.ecr-reponame }}' >> $env:GITHUB_ENV
    - name:
      shell: pwsh
      run: |
        Write-Host -Object ('Amazon ECR registry is: {0}' -f ${env:ecr-registry})
    - name: Install AWS PowerShell Modules
      shell: pwsh
      run: |
        Install-Module -Name AWS.Tools.ECR, AWS.Tools.ECS, AWS.Tools.CloudFormation -Scope CurrentUser -Force
        Write-Host -Object (Get-Module -ListAvailable -Name AWS.Tools.*).Path
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Create Amazon ECR Registry
      shell: pwsh
      continue-on-error: true
      run: |
        New-ECRRepository -RepositoryName ${{ env.ecr-reponame }}
    - name: Create Amazon ECS Cluster
      shell: pwsh
      continue-on-error: true
      run: |
        New-ECSCluster -ClusterName ${{ env.ecs-cluster-name }}
    # - name: Create Amazon ECS Task Definition
    #   shell: pwsh
    #   continue-on-error: true
    #   run: |
    #     New-ECSCluster -ClusterName ${{ env.ecs-cluster-name }}
    - name: Docker Login to Amazon Elastic Container Registry (ECR)
      uses: docker/login-action@v1
      with:
        registry: ${{ env.ecr-registry }}
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Build Container Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.ecr-repository }}:latest
